CREATE TABLE `rdv` (
  `date_debut` date NOT NULL default '0000-00-00',
  `heure_debut` time NOT NULL default '00:00:00',
  `date_fin` date NOT NULL default '0000-00-00',
  `heure_fin` time NOT NULL default '00:00:00',
  `dossier` varchar(255) NOT NULL default '',
  `rdv_pour` varchar(255) NOT NULL default '',
  `rdv_grp` varchar(255) NOT NULL default '',
  `libelle` varchar(255) NOT NULL default '',
  `lieu` varchar(255) NOT NULL default '',
  `repete` char(1) NOT NULL default '',
  `biffe` char(1) NOT NULL default '',
  `repete_fin` date NOT NULL default '0000-00-00',
  `type` varchar(64) NOT NULL default '',
  `np` varchar(32) NOT NULL default '',
  `nple` date NOT NULL default '0000-00-00',
  `mp` varchar(32) NOT NULL default '',
  `mple` date NOT NULL default '0000-00-00',
  `id` int(11) unsigned NOT NULL auto_increment,
  `reserveid` int(11) unsigned NOT NULL default '0',
  `priorite` varchar(255) NOT NULL default '',
  `status` int(2) NOT NULL default '0',
  `doodle` varchar(255) NOT NULL default '',
  `doodleid` varchar(255) NOT NULL default '',
  `doodleset` varchar(255) NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
