CREATE TABLE `adresses` (
  `type` varchar(64) NOT NULL default '',
  `typesociete` varchar(4) NOT NULL default '',
  `nosociete` varchar(64) NOT NULL default '',
  `test` varchar(32) NOT NULL default '',
  `titre` varchar(65) NOT NULL default '',
  `nom` varchar(255) NOT NULL default '',
  `prenom` varchar(255) NOT NULL default '',
  `adresse` varchar(255) NOT NULL default '',
  `fonction` varchar(255) NOT NULL default '',
  `cp` varchar(32) NOT NULL default '',
  `zip` varchar(32) NOT NULL default '',
  `ville` varchar(64) NOT NULL default '',
  `canton` varchar(64) NOT NULL default '',
  `pays` varchar(64) NOT NULL default '',
  `tel` varchar(32) NOT NULL default '',
  `fax` varchar(32) NOT NULL default '',
  `natel` varchar(32) NOT NULL default '',
  `autrestel` varchar(32) NOT NULL default '',
  `telprive` varchar(32) NOT NULL default '',
  `faxprive` varchar(32) NOT NULL default '',
  `natelprive` varchar(32) NOT NULL default '',
  `mail` varchar(64) NOT NULL default '',
  `mailprive` varchar(64) NOT NULL default '',
  `rem` text NOT NULL default '',
  `np` varchar(32) NOT NULL default '',
  `nple` date NOT NULL default '0000-00-00',
  `mp` varchar(32) NOT NULL default '',
  `mple` date NOT NULL default '0000-00-00',
  `ccp` varchar(64) NOT NULL default '',
  `salut` varchar(32) NOT NULL default '',
  `id` int(11) unsigned NOT NULL auto_increment,
  `corps` longtext NOT NULL default '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
