CREATE TABLE `to_preg` (
  `nodossier` int(11) NOT NULL default '0',
  `enattente` tinyint(1) NOT NULL default '0',
  `dateop` date NOT NULL default '0000-00-00',
  `op` varchar(255) NOT NULL default '',
  `opavec` varchar(255) NOT NULL default '',
  `tempsop` time NOT NULL default '00:00:00',
  `dateac` date NOT NULL default '0000-00-00',
  `ac` varchar(255) NOT NULL default '',
  `acpar` varchar(255) NOT NULL default '',
  `encaissement` decimal(10,2) NOT NULL default '0.00',
  `provision` decimal(10,2) NOT NULL default '0.00',
  `depens` decimal(10,2) NOT NULL default '0.00',
  `avfrais` decimal(10,2) NOT NULL default '0.00',
  `demande` decimal(10,2) NOT NULL default '0.00',
  `transit` decimal(10,2) NOT NULL default '0.00',
  `forfait` decimal(10,2) NOT NULL default '0.00',
  `facturesanstemps` decimal(10,2) NOT NULL default '0.00',
  `facture` decimal(10,2) NOT NULL default '0.00',
  `facturepayee` int(1) NOT NULL default '0',
  `idfacture` varchar(64) NOT NULL default '',
  `idop` int(11) NOT NULL auto_increment,
  `np` varchar(64) NOT NULL default '',
  `nple` date NOT NULL default '0000-00-00',
  `mp` varchar(64) NOT NULL default '',
  `mple` date NOT NULL default '0000-00-00',
  `soustraitant` varchar(64) NOT NULL default '',
  `tvaop` decimal(10,2) NOT NULL default '-100.00',
  PRIMARY KEY  (`idop`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
