CREATE TABLE `utilisateurs` (
  `nou` int(11) NOT NULL auto_increment,
  `initiales` char(2) NOT NULL,
  `nom` varchar(64) NOT NULL,
  `ouverture` varchar(64) NOT NULL,
  `couleur` char(7) NOT NULL,
  `seul` tinyint(1) NOT NULL default '0',
  `currency` varchar(64) NOT NULL,
  `tx_tva` decimal(4,2) NOT NULL default '8.0',
  `tx_f_tva` decimal(4,2) NOT NULL default '6.1',
  `tx_var_tva` varchar(255) NOT NULL default '0.00=0.00;7.60=5.80;8.00=6.10',
  `prix_defaut` decimal(6,2) NOT NULL default '350.00',
  `racine` varchar(255) NOT NULL,
  `racine_webdav` varchar(255) NOT NULL,
  `use_webdav` tinyint(1) NOT NULL default '0',
  `racine_mbx` varchar(255) NOT NULL,
  `user_mbx` varchar(255) NOT NULL,
  `pass_mbx` varchar(255) NOT NULL,
  `ltype` text NOT NULL,
  `dossiers_type` text NOT NULL,
  `op_type` text NOT NULL,
  `ac_type` text NOT NULL,
  `matiere_type` text NOT NULL,
  `delais_type` text NOT NULL,
  `soustraitants` text NOT NULL,
  `rdv_type` text NOT NULL,
  `origine_mandat` text NOT NULL,
  `tva_deb` int(1) NOT NULL default '1',
  `lieux` text NOT NULL,
  `bibliotheques` text NOT NULL,
  `archive` int(1) NOT NULL default '0',
  `doodle` varchar(255) NOT NULL default '',
  `mailing` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`nou`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
